# Generated by Django 5.1.1 on 2025-07-31 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generaluser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='generaluser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='generaluser',
            name='is_superuser',
        ),
    ]
