# Generated by Django 5.1.1 on 2025-07-31 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_generaluser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluser',
            name='photo_Generaluser',
            field=models.ImageField(blank=True, upload_to='generaluser/profile_photo'),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='photo_staffuser',
            field=models.ImageField(blank=True, upload_to='staffuser/profile_photo'),
        ),
        migrations.AddField(
            model_name='superuser',
            name='photo_superuser',
            field=models.ImageField(blank=True, upload_to='superuser/profile_photo'),
        ),
    ]
