# Generated by Django 5.1.1 on 2025-07-31 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_generaluser_photo_generaluser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generaluser',
            old_name='photo_Generaluser',
            new_name='photo_generaluser',
        ),
    ]
