# Generated by Django 5.1.1 on 2025-08-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_photo_generaluser_generaluser_photo_generaluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaluser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staffuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='superuser',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
