# Generated by Django 5.1.1 on 2025-08-29 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_generaluser_password_staffuser_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generaluser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='staffuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
